export const DEFAULT_SETTINGS = {
  worldWidth: 1000,
  worldHeight: 650,
  challengeDuration: 480,

  playerSpeed: 100,
  playerLives: 5,
  playerSprintMultiplier: 2.2,
  playerSprintDuration: 3,
  playerSprintCooldown: 1.2,
  playerDashDistance: 110,
  playerDashCooldown: 1.1,
  playerDashEffectDuration: 0.18,

  chickenAlertRadius: 150,
  chickenPressureRadius: 95,
  chickenPanicRadius: 45,

  chickenWanderSpeed: 22,
  chickenEscapeSpeed: 80,
  chickenPanicSpeed: 125,
  chickenEscapeBurstMultiplier: 3.4,
  chickenPanicBurstMultiplier: 4.8,
  roosterEscapeSpeed: 90,
  roosterPanicSpeed: 135,
  roosterAttackTelegraphTime: 3,
  roosterAttackSpeed: 560,
  roosterAttackDistance: 430,
  roosterAttackRecoverTime: 1.1,
  roosterAttackMinInterval: 12,
  roosterAttackMaxInterval: 12,
  roosterRageRadius: 480,
  roosterRageTimeout: 10,
  roosterEscapeChaseThreshold: 3,
  roosterEscapeChaseWindow: 7,

  escapeConeAngle: 90,
  escapeDistribution: "center",
  escapeExitBuffer: 90,
  minimumEscapeDistance: 130,
  maximumEscapeDistance: 230,
  minimumDirectionLockTime: 0.55,
  maximumDirectionLockTime: 0.9,

  grainAmountPerDrop: 10,
  grainDropCount: 3,
  grainRechargeInterval: 10,
  grainAttractionRadius: 220,
  grainPlayerExclusionRadius: 130,
  grainCoopGateExclusionRadius: 60,
  grainConsumeInterval: 1,
  grainLifetime: 10,

  coopRequiredStayTime: 0.6,
  coopGateWidth: 54,
  coopWallThickness: 12,

  clapWaveSpeed: 560,
  clapWaveRadius: 360,
  clapWaveWidth: 28,
  clapPanicSpeed: 330,
  clapRunDistance: 150,
  clapDirectionLockTime: 0.75,

  debugShowRadii: true,
  debugShowState: true,
  debugShowCone: true,
  debugShowDirection: true,
  debugShowCollision: false
};
